-- Questão 1 --


-- Questão 2 --
SELECT COD_TIME, NOME_TIME, (COUNT(COD_TIME_MANDANTE) + COUNT(COD_TIME_VISITANTE)) NUMERO_PARTIDASS FROM JOGO
JOIN TIME ON COD_TIME_MANDANTE = COD_TIME
GROUP BY COD_TIME_MANDANTE, COD_TIME;

-- Questão 3 --
CREATE OR REPLACE VIEW GOLS_FLAMENGO_PONTUADO AS
SELECT NOME_TIME, (SUM(NUM_GOLS_TIME_MANDANTE) + SUM(NUM_GOLS_TIME_VISITANTE)) GOLS_FLAMENGO FROM JOGO
JOIN TIME ON COD_TIME = COD_TIME_MANDANTE
WHERE COD_TIME = 5
GROUP BY NOME_TIME, NUM_GOLS_TIME_MANDANTE
;

CREATE OR REPLACE VIEW GOLS_FLAMENGO_SOFRIDOS AS
SELECT NOME_TIME, (SUM(NUM_GOLS_TIME_MANDANTE) + SUM(NUM_GOLS_TIME_VISITANTE)) GOLS_CONTRA_FLAMENGO FROM JOGO
JOIN TIME ON COD_TIME = COD_TIME_MANDANTE
WHERE (COD_TIME_MANDANTE = 5 AND COD_TIME_VISITANTE != 5) OR (COD_TIME_MANDANTE != 5 AND COD_TIME_VISITANTE = 5)
AND NOME_TIME NOT ILIKE 'FLAMENGO'
GROUP BY NOME_TIME, NUM_GOLS_TIME_MANDANTE
;

SELECT (SUM(GOLS_FLAMENGO) - SUM(GOLS_CONTRA_FLAMENGO)) FROM GOLS_FLAMENGO_PONTUADO
JOIN GOLS_FLAMENGO_SOFRIDOS ON GOLS_FLAMENGO_PONTUADO.NOME_TIME = GOLS_FLAMENGO_SOFRIDOS.NOME_TIME;



-- Questão 4 --
CREATE OR REPLACE FUNCTION MAXIMA_CONTRATACOES()
RETURNS TRIGGER
AS $$
BEGIN
	IF (NEW.CONTRATACAO_ATIVA = 's') THEN
		IF (((SELECT COUNT(CONTRATACAO_ATIVA) FROM JOGATIME WHERE COD_TIME = NEW.COD_TIME) >= 
			(SELECT NUM_MAXIMO_CONTRATADOS FROM TIME WHERE COD_TIME = NEW.COD_TIME))) THEN
			RAISE EXCEPTION 'Limite de contratações atingidas';
		END IF;
	END IF;
RETURN NEW;
END;
$$
LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER TG_MAXIMA_CONTRATACOES
BEFORE INSERT OR UPDATE
ON JOGATIME
FOR EACH ROW
EXECUTE FUNCTION MAXIMA_CONTRATACOES();

