CREATE TABLE VENDA(
	Cod_venda INT PRIMARY KEY,
	Nome_vendedor VARCHAR(50) NOT NULL,
	data_venda DATE NOT NULL,
	Valor_vendido FLOAT NOT NULL
)

--Reposta da Questão 1--

INSERT INTO VENDA (Cod_venda, Nome_vendedor, data_venda, Valor_vendido)
VALUES 
(1, 'Arthur', '2024-04-12', 250.0),
(2, 'Maria', '2024-04-11', 250.0),
(3, 'João', '2024-04-10', 320.0),
(4, 'Lucia', '2024-04-09', 180.0),
(5, 'Carlos', '2024-04-08', 400.0),
(6, 'Fernanda', '2024-04-07', 275.5),
(7, 'Pedro', '2024-04-06', 150.0),
(8, 'Juliana', '2024-04-05', 600.0),
(9, 'Bruno', '2024-04-04', 500.0),
(10, 'Ana', '2024-04-03', 350.0);

UPDATE VENDA 
SET data_venda = '2024-03-10'
WHERE nome_vendedor in ('Arthur', 'Bruno');

UPDATE VENDA
SET VALOR_VENDIDO = 500
WHERE NOME_VENDEDOR = 'Arthur';

-- Resposta da Questão 2.1 --
CREATE OR REPLACE VIEW VENDAS_MAIOR_350_MARCO AS
SELECT Nome_vendedor FROM VENDA WHERE Valor_vendido > 350 
AND data_venda BETWEEN '2024-03-01' AND '2024-03-31';

SELECT * FROM VENDAS_MAIOR_350_MARCO;

-- Resposta da Questão 2.1 (Prof) --
SELECT NOME_VENDEDOR, SUM(VALOR_VENDIDO) TOTAL_VENDIDO 
FROM VENDA WHERE DATA_VENDA 
BETWEEN '2024-03-01' AND '2024-03-31'
GROUP BY NOME_VENDEDOR ORDER BY TOTAL_VENDIDO DESC;

-- Feita com Extract --
/* Extract serve para ver o valor em geral
   por exemplo ver todos os anos de um mês em 
   especifico 
*/
SELECT NOME_VENDEDOR, SUM(VALOR_VENDIDO) TOTAL_VENDIDO
FROM VENDA
WHERE EXTRACT (YEAR FROM DATA_VENDA) = 2024 AND 
EXTRACT (MONTH FROM DATA_VENDA) = 3
GROUP BY NOME_VENDEDOR HAVING SUM (VALOR_VENDIDO) > 900
ORDER BY TOTAL_VENDIDO DESC;

--Resposta da Questão 2.2--
SELECT NOME_VENDEDOR, SUM(VALOR_VENDIDO) TOTAL_VENDIDO
FROM VENDA
WHERE EXTRACT (YEAR FROM DATA_VENDA) = 2024 AND 
EXTRACT (MONTH FROM DATA_VENDA) = 3
GROUP BY NOME_VENDEDOR
ORDER BY TOTAL_VENDIDO DESC LIMIT 1;

-- Respota da Questão 3 --
CREATE VIEW TOTAL_VENDAS AS
SELECT NOME_VENDEDOR, SUM(VALOR_VENDIDO) TOTAL_VENDIDO
FROM VENDA
WHERE EXTRACT (YEAR FROM DATA_VENDA) = 2024 AND 
EXTRACT (MONTH FROM DATA_VENDA) = 3
GROUP BY NOME_VENDEDOR
ORDER BY TOTAL_VENDIDO DESC;

SELECT NOME_VENDEDOR, TOTAL_VENDIDO FROM TOTAL_VENDAS
WHERE TOTAL_VENDIDO = (SELECT MAX(TOTAL_VENDIDO) 
FROM TOTAL_VENDAS);
