CREATE TABLE CATEGORIA 
(COD_CAT SERIAL PRIMARY KEY, NOME VARCHAR(100), PRECO INT, DESCRICAO TEXT);
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('LUXO', 300, 'PARA RICOS');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('DUBLE', 200, 'PARA DUBLES');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('MEDIO', 150, 'CLASSE MEDIA');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('POBRE', 100, 'PARA POBRES');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('ECONÔMICO', 120, 'Básico, para estadias curtas');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('EXECUTIVO', 250, 'Mais conforto para negócios');


CREATE TABLE APARTAMENTO 
(NUM_AP SERIAL PRIMARY KEY, COD_CAT INT,
FOREIGN KEY (COD_CAT) REFERENCES CATEGORIA(COD_CAT));
INSERT INTO APARTAMENTO (COD_CAT) VALUES (1);  -- LUXO
INSERT INTO APARTAMENTO (COD_CAT) VALUES (2);  -- DUBLE
INSERT INTO APARTAMENTO (COD_CAT) VALUES (3);  -- MEDIO
INSERT INTO APARTAMENTO (COD_CAT) VALUES (4);  -- POBRE
INSERT INTO APARTAMENTO (COD_CAT) VALUES (5);  -- ECONÔMICO
INSERT INTO APARTAMENTO (COD_CAT) VALUES (6);  -- EXECUTIVO
INSERT INTO APARTAMENTO (COD_CAT) VALUES (1);  -- LUXO
INSERT INTO APARTAMENTO (COD_CAT) VALUES (3);  -- MEDIO
INSERT INTO APARTAMENTO (COD_CAT) VALUES (5);  -- ECONÔMICO
INSERT INTO APARTAMENTO (COD_CAT) VALUES (6);  -- EXECUTIVO


CREATE TABLE HOSPEDAGEM 
(COD_HOSPEDAGEM SERIAL PRIMARY KEY, NUM_AP INT, COD_HOSP INT, COD_FUNC INT, DT_ENT DATE, DT_SAIDA DATE,
FOREIGN KEY (NUM_AP) REFERENCES APARTAMENTO(NUM_AP),
FOREIGN KEY (COD_HOSP) REFERENCES HOSPEDE(COD_HOSP),
FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC));
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (1, 1, 1, '2025-1-1', '2025-1-2');
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (2, 2, 2, '2025-1-1', '2025-1-3');
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (3, 3, 3, '2025-1-1', '2025-1-4');
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (4, 4, 4, '2025-1-1', NULL);
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (5, 5, 1, '2025-02-01', '2025-02-03');   -- MARCOS
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (6, 6, 2, '2025-02-02', NULL);           -- LUANA (ainda hospedada)
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (7, 7, 3, '2025-02-03', '2025-02-04');   -- JUAN
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (8, 8, 4, '2025-02-05', '2025-02-06');   -- MARIA
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (9, 9, 1, '2025-02-06', NULL);           -- PEDRO
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (10, 10, 2, '2025-02-07', '2025-02-10'); -- ANA
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (1, 11, 3, '2025-02-08', NULL);          -- IVAN (reusando apto 1)
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (2, 12, 4, '2025-02-09', '2025-02-12');  -- SANDRA
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (3, 13, 1, '2025-02-10', NULL);          -- DIEGO
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (4, 14, 2, '2025-02-11', NULL);          -- FELIPE
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (5, 15, 3, '2025-02-12', NULL);          -- CLARA


CREATE TABLE HOSPEDE 
(COD_HOSP SERIAL PRIMARY KEY, NOME VARCHAR(100), DT_NASC DATE);
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('CHICO', '2005-1-6');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('JOAO', '1967-3-20');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('DONA ANGELA', '1972-12-8');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('CHICA', '2005-7-10');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('MARCOS', '1990-05-12');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('LUANA', '1985-11-30');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('JUAN', '1995-02-25');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('MARIA', '2001-06-18');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('PEDRO', '1982-03-09');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('ANA', '1999-12-01');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('IVAN', '1975-07-04');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('SANDRA', '1993-10-10');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('DIEGO', '1988-09-22');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('FELIPE', '2004-04-14');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('CLARA', '2003-08-29');



CREATE TABLE FUNCIONARIO (COD_FUNC SERIAL PRIMARY KEY, NOME VARCHAR(100), DT_NASC DATE);
INSERT INTO FUNCIONARIO (NOME, DT_NASC)
VALUES ('RABICO', '1960-10-5');
INSERT INTO FUNCIONARIO (NOME, DT_NASC)
VALUES ('ADOLFO', '2000-3-20');
INSERT INTO FUNCIONARIO (NOME, DT_NASC)
VALUES ('RITA', '2000-5-29');
INSERT INTO FUNCIONARIO (NOME, DT_NASC)
VALUES ('CLEITON', '1980-3-20');

ALTER TABLE FUNCIONARIO ADD COLUMN SALARIO NUMERIC(10, 2);

UPDATE FUNCIONARIO SET SALARIO = 3000.00 WHERE NOME = 'RABICO';
UPDATE FUNCIONARIO SET SALARIO = 2500.00 WHERE NOME = 'ADOLFO';
UPDATE FUNCIONARIO SET SALARIO = 2700.00 WHERE NOME = 'RITA';
UPDATE FUNCIONARIO SET SALARIO = 3100.00 WHERE NOME = 'CLEITON';


ALTER TABLE HOSPEDE 
ADD COLUMN NAC VARCHAR (100);
UPDATE HOSPEDE
SET NAC = 'ANGOLANO'
WHERE NOME = 'CHICO';
UPDATE HOSPEDE 
SET NAC = 'BRASILEIRO'
WHERE NOME = 'JOAO';
UPDATE HOSPEDE 
SET NAC = 'URUGUAIA'
WHERE NOME = 'DONA ANGELA';
UPDATE HOSPEDE
SET NAC = 'MEXICANA'
WHERE NOME = 'CHICA';

UPDATE CATEGORIA 
SET PRECO = PRECO * 1.10;

-- Atualizando as categorias com novos nomes, descrições e preços
UPDATE CATEGORIA 
SET NOME = 'ECONOMICA', 
    DESCRICAO = 'Básica, para estadias curtas', 
    PRECO = 120 
WHERE COD_CAT = 1;

UPDATE CATEGORIA 
SET NOME = 'EXECUTIVA', 
    DESCRICAO = 'Conforto padrão para negócios', 
    PRECO = 200 
WHERE COD_CAT = 2;

UPDATE CATEGORIA 
SET NOME = 'EXECUTIVA PREMIUM', 
    DESCRICAO = 'Mais conforto e comodidades para trabalho', 
    PRECO = 250 
WHERE COD_CAT = 3;

UPDATE CATEGORIA 
SET NOME = 'LUXO', 
    DESCRICAO = 'Acomodação de alto padrão', 
    PRECO = 300 
WHERE COD_CAT = 4;

UPDATE CATEGORIA 
SET NOME = 'SUPER LUXO', 
    DESCRICAO = 'Serviços exclusivos e ambiente requintado', 
    PRECO = 400 
WHERE COD_CAT = 5;

UPDATE CATEGORIA 
SET NOME = 'PRESIDENCIAL', 
    DESCRICAO = 'Máximo conforto, luxo e privacidade', 
    PRECO = 500 
WHERE COD_CAT = 6;

INSERT INTO CATEGORIA 
VALUES(7, 'MILIONÁRIO', 1000, 'Tudo de melhor no mundo');

INSERT INTO HOSPEDAGEM VALUES(16, 5, 2, 2, '2025-12-02', '2026-12-02');
INSERT INTO HOSPEDAGEM VALUES(17, 5, 2, 2, '2024-12-02', '2027-12-02');
INSERT INTO HOSPEDAGEM VALUES(18, 6, 4, 2, '2017-12-02', '2017-12-02');

-- So pra teste -- 
UPDATE CATEGORIA
SET PRECO = 100
WHERE NOME = 'MILIONÁRIO';
